STATE_NONE = 0
STATE_EDITOR = 1
STATE_INSPECT = 2
STATE_PREPARE = 3
STATE_AVAILABLEEVENTS = 4
STATE_PREJOIN = 5
STATE_JOINED = 6
STATE_RACING = 7
STATE_AFTERRACE = 8

RACETYPE_SPRINT = 0
RACETYPE_CIRCUIT = 1
RACETYPE_DRIFT = 2
RACETYPE_DRIFTCIRCUIT = 3

ALLCAR = '-1'